#!/bin/bash -x

for i in `cat /Users/dsiegfriedt/short-name-list`
do
echo ""
NEW=`cat /Users/dsiegfriedt/DOCs/machine-name-list-27apr09 | grep -v edmunds.com | grep $i`
echo "Dollar i is $i"
echo "Dollar NEW is $NEW"
#sed s/$i/$NEW/ /Users/dsiegfriedt/LAX1_Elevations_07222009.csv > FQMN-list.txt
done



# 21aug09 NOTES  (this will give a list of FQHN from LAX1_Elevations_07222009.csv.
#
# for i in `cat LAX1_Elevations_07222009.csv | sed '1,4d' | grep -v edmunds.com | awk -F, '{print $2}'`; do echo $i; NEW=`host $i | awk '{print $1}'`; echo $NEW; done


