#!/bin/bash

#From https://bbs.archlinux.org/viewtopic.php?id=36305
# Used 20Feb14 to rename Audio book files.

ls | while read -r FILE
do
    mv -v "$FILE" `echo $FILE | tr ' ' '_' | tr -d '[{}(),\!]' | tr -d "\'" | tr '[A-Z]' '[a-z]' | sed 's/_-_/_/g'`
done